server:
  port: 8100
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #  sql:
  #    init:
  #      platform: h2
  #      schema-locations: classpath:db/schema.sql
  #      data-locations: classpath:db/data.sql
  jpa:
    show-sql: true
    #设置ddl模式
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: h2
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect



  ##数据库连接设置
  datasource:
    driverClassName: org.h2.Driver
    #可执行程序的当前路径
    url: jdbc:h2:file:./data/jpa-dynamic
    #指定的静态配置路径
    username: h2
    password: h2
  # 进行该配置后，h2 web console就可以在远程访问了。否则只能在本机访问。
  h2:
    console:
      settings:
        web-allow-others: true
      #进行该配置，你就可以通过YOUR_URL/h2访问h2 web console。YOUR_URL是你程序的访问URl。
      path: /h2
      #进行该配置，程序开启时就会启动h2 web console。当然这是默认的，如果你不想在启动程序时启动h2 web console，那么就设置为false。
      enabled: true
springdoc:
  swagger-ui:
    path: swagger
