#camunda 配置
camunda:
  bpm:
    generic-properties.properties:
      javaSerializationFormatEnabled: true
    # 配置账户密码来访问Camunda自带的管理界面
    admin-user:
      id: admin
      password: admin
      first-name: admin
    filter:
      create: All tasks
    database:
      type: mysql
      # 数据库内没有相关流程表时，将schema-update设置为 true，可以自动创建表
      # 数据库内已经存在相关流程表时，schema-update 设置为 false
      schema-update: false
    metrics:
      enabled: false
      db-reporter-activate: false
    # 禁止自动部署resources下面的bpmn文件
    auto-deployment-enabled: false
    # 事件流的是否开启（默认全部开启状态）
    eventing:
      # 控制执行事件流是否开启
      execution: true
      # 历史事件流是否开启
      history: true
      # 任务事件流是否开启
      task: true
    # 禁止index跳转到Camunda自带的管理界面，默认true
#    webapp:
#      index-redirect-enabled: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/camunda_demo?characterEncoding=UTF-8&useUnicode=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: pw123456
logging:
  level:
    com.dzero.wf.camunda.demo: info
    org.camunda.bpm.engine: info
    o.a.ibatis: info
#服务端口
server:
  port: 8081