#camunda 配置
camunda:
  bpm:
    # 配置账户密码来访问Camunda自带的管理界面
    admin-user:
      id: admin
      password: admin
      first-name: admin
    filter:
      create: All tasks
    database:
      type: mysql
      # 数据库内没有相关流程表时，将schema-update设置为true，可以自动创建表
      # 数据库内已经存在相关流程表时，schema-update 设置为 false
      schema-update: false
    metrics:
      enabled: false
      db-reporter-activate: false
    # 禁止自动部署resources下面的bpmn文件
    auto-deployment-enabled: false
    # 禁止index跳转到Camunda自带的管理界面，默认true
#    webapp:
#      index-redirect-enabled: false
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/camunda_demo?characterEncoding=UTF-8&useUnicode=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: pw123456
#服务端口
server:
  port: 8081